// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMYMl_2OwfSUfsXqtiY-lJKYCP0soFb3g',
    appId: '1:718544240058:web:775b9047cda5f2a0007183',
    messagingSenderId: '718544240058',
    projectId: 'on-chat-aeeb7',
    authDomain: 'on-chat-aeeb7.firebaseapp.com',
    storageBucket: 'on-chat-aeeb7.appspot.com',
    measurementId: 'G-Q1NDPHX43V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAH9qPR-e5mHt-JpBfhI8PJ0XlrFSUqIOc',
    appId: '1:718544240058:android:03534147ce920fdd007183',
    messagingSenderId: '718544240058',
    projectId: 'on-chat-aeeb7',
    storageBucket: 'on-chat-aeeb7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzg_A7OQHTK9n2Bt-CZB96wL-1hctroyA',
    appId: '1:718544240058:ios:53173db57d976087007183',
    messagingSenderId: '718544240058',
    projectId: 'on-chat-aeeb7',
    storageBucket: 'on-chat-aeeb7.appspot.com',
    iosClientId: '718544240058-na050drvgrdhlos3qtkupjopvp34td2k.apps.googleusercontent.com',
    iosBundleId: 'com.example.onChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzg_A7OQHTK9n2Bt-CZB96wL-1hctroyA',
    appId: '1:718544240058:ios:4726312e8216e322007183',
    messagingSenderId: '718544240058',
    projectId: 'on-chat-aeeb7',
    storageBucket: 'on-chat-aeeb7.appspot.com',
    iosClientId: '718544240058-uqo68pm7n3pfd5ffjj6q8t0q9mc97l22.apps.googleusercontent.com',
    iosBundleId: 'com.example.onChat.RunnerTests',
  );
}
